// src/constants/banks.js

export const BANKS = [
    // Ngân hàng Thương mại Nhà nước
    { value: 'Agribank', label: 'Agribank - Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam' },
    { value: 'BIDV', label: 'BIDV - Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam' },
    { value: 'CB', label: 'CB - Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam' },
    { value: 'GPBank', label: 'GPBank - Ngân hàng Thương mại TNHH MTV Dầu khí Toàn cầu' },
    { value: 'Oceanbank', label: 'Oceanbank - Ngân hàng Thương mại TNHH MTV Đại Dương' },
    { value: 'Vietcombank', label: 'Vietcombank - Ngân hàng Thương mại Cổ phần Ngoại thương Việt Nam' },
    { value: 'Vietinbank', label: 'Vietinbank - Ngân hàng Thương mại Cổ phần Công thương Việt Nam' },
  
    // Ngân hàng Thương mại Cổ phần
    { value: 'ABBank', label: 'ABBank - Ngân hàng TMCP An Bình' },
    { value: 'ACB', label: 'ACB - Ngân hàng TMCP Á Châu' },
    { value: 'Bac A Bank', label: 'Bac A Bank - Ngân hàng TMCP Bắc Á' },
    { value: 'Bao Viet Bank', label: 'Bao Viet Bank - Ngân hàng TMCP Bảo Việt' },
    { value: 'BVBank', label: 'BVBank - Ngân hàng TMCP Bản Việt (Viet Capital Bank)' },
    { value: 'DongA Bank', label: 'DongA Bank - Ngân hàng TMCP Đông Á' },
    { value: 'Eximbank', label: 'Eximbank - Ngân hàng TMCP Xuất Nhập khẩu Việt Nam' },
    { value: 'Great Asia Bank', label: 'Great Asia Bank - Ngân hàng TMCP Đại Á' },
    { value: 'Great Trust Bank', label: 'Great Trust Bank - Ngân hàng TMCP Tin Nghĩa' },
    { value: 'HDBank', label: 'HDBank - Ngân hàng TMCP Phát triển TP. HCM' },
    { value: 'KienLongBank', label: 'KienLongBank - Ngân hàng TMCP Kiên Long' },
    { value: 'LienVietPostBank', label: 'LienVietPostBank - Ngân hàng TMCP Liên Việt Bưu Điện' },
    { value: 'LPBank', label: 'LPBank - Ngân hàng TMCP Lộc Phát Việt Nam' },
    { value: 'MBBank', label: 'MBBank - Ngân hàng TMCP Quân Đội' },
    { value: 'Mekong Commercial Bank', label: 'Mekong Commercial Bank - Ngân hàng TMCP Mê Kông' },
    { value: 'Mekong Development Bank', label: 'Mekong Development Bank - Ngân hàng TMCP Phát triển Mê Kông' },
    { value: 'MSB', label: 'MSB - Ngân hàng TMCP Hàng Hải Việt Nam' },
    { value: 'Nam A Bank', label: 'Nam A Bank - Ngân hàng TMCP Nam Á' },
    { value: 'Nam Viet Bank', label: 'Nam Viet Bank - Ngân hàng TMCP Nam Việt' },
    { value: 'NCB', label: 'NCB - Ngân hàng TMCP Quốc Dân' },
    { value: 'OCB', label: 'OCB - Ngân hàng TMCP Phương Đông' },
    { value: 'PG Bank', label: 'PG Bank - Ngân hàng TMCP Petrolimex' },
    { value: 'PVcomBank', label: 'PVcomBank - Ngân hàng TMCP Đại Chúng Việt Nam' },
    { value: 'Sacombank', label: 'Sacombank - Ngân hàng TMCP Sài Gòn Thương Tín' },
    { value: 'SaigonBank', label: 'SaigonBank - Ngân hàng TMCP Sài Gòn Công Thương' },
    { value: 'SCB', label: 'SCB - Ngân hàng TMCP Sài Gòn' },
    { value: 'SeABank', label: 'SeABank - Ngân hàng TMCP Đông Nam Á' },
    { value: 'SHB', label: 'SHB - Ngân hàng TMCP Sài Gòn - Hà Nội' },
    { value: 'Techcombank', label: 'Techcombank - Ngân hàng TMCP Kỹ Thương Việt Nam' },
    { value: 'TPBank', label: 'TPBank - Ngân hàng TMCP Tiên Phong' },
    { value: 'VIB', label: 'VIB - Ngân hàng TMCP Quốc tế Việt Nam' },
    { value: 'Viet A Bank', label: 'Viet A Bank - Ngân hàng TMCP Việt Á' },
    { value: 'VietBank', label: 'VietBank - Ngân hàng TMCP Việt Nam Thương Tín' },
    { value: 'VPBank', label: 'VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng' },
    { value: 'Western Bank', label: 'Western Bank - Ngân hàng TMCP Phương Tây' },
  ];